version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb_local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/ainav
      - PORT=3000
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data:
